"""phase5 notification

Revision ID: 0faa79e4ebe7
Revises: c93b2b96f21e
Create Date: 2026-06-11 15:48:11.839155
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0faa79e4ebe7'
down_revision: Union[str, None] = 'c93b2b96f21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('patient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('appointment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    op.create_table('email_logs',
    sa.Column('email_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('to_email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_msg_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_notification_id'), ['notification_id'], unique=False)

    op.create_table('push_notifications',
    sa.Column('push_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('device_token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('push_id')
    )
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_notifications_notification_id'), ['notification_id'], unique=False)

    op.create_table('sms_logs',
    sa.Column('sms_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_msg_id', sa.String(length=100), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('sms_id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_notification_id'), ['notification_id'], unique=False)

    op.create_table('whatsapp_logs',
    sa.Column('wa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_msg_id', sa.String(length=100), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.PrimaryKeyConstraint('wa_id')
    )
    with op.batch_alter_table('whatsapp_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_logs_notification_id'), ['notification_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_logs_notification_id'))

    op.drop_table('whatsapp_logs')
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_notification_id'))

    op.drop_table('sms_logs')
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_notifications_notification_id'))

    op.drop_table('push_notifications')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_notification_id'))

    op.drop_table('email_logs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_patient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_hospital_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
