"""phase2 doctor and reception

Revision ID: 176b7b26907a
Revises: 5ec4179742a5
Create Date: 2026-06-11 14:28:23.172928
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176b7b26907a'
down_revision: Union[str, None] = '5ec4179742a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('department_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('languages', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_available_today', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_user_id'), ['user_id'], unique=False)

    op.create_table('receptionists',
    sa.Column('receptionist_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('departments_assigned', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('receptionist_id')
    )
    with op.batch_alter_table('receptionists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receptionists_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receptionists_user_id'), ['user_id'], unique=False)

    op.create_table('doctor_delay_logs',
    sa.Column('delay_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('delay_date', sa.Date(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('notified_patients', sa.Boolean(), nullable=False),
    sa.Column('logged_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('delay_id')
    )
    with op.batch_alter_table('doctor_delay_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_delay_logs_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('doctor_holidays',
    sa.Column('holiday_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('is_full_day', sa.Boolean(), nullable=False),
    sa.Column('partial_start', sa.Time(), nullable=True),
    sa.Column('partial_end', sa.Time(), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    with op.batch_alter_table('doctor_holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_holidays_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('doctor_leave_requests',
    sa.Column('leave_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('leave_from', sa.Date(), nullable=False),
    sa.Column('leave_to', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('approved_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('leave_id')
    )
    with op.batch_alter_table('doctor_leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_leave_requests_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_leave_requests_status'), ['status'], unique=False)

    op.create_table('doctor_schedule',
    sa.Column('schedule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('day_of_week', sa.String(length=3), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('consultation_mins', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_schedule_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('doctor_status',
    sa.Column('status_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('current_token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('tokens_served_today', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_table('receptionist_shift',
    sa.Column('shift_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('receptionist_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('department_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['receptionist_id'], ['receptionists.receptionist_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    with op.batch_alter_table('receptionist_shift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receptionist_shift_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receptionist_shift_receptionist_id'), ['receptionist_id'], unique=False)

    op.create_table('doctor_breaks',
    sa.Column('break_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=False),
    sa.Column('break_end', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['doctor_schedule.schedule_id'], ),
    sa.PrimaryKeyConstraint('break_id')
    )
    with op.batch_alter_table('doctor_breaks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_breaks_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_breaks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_breaks_schedule_id'))

    op.drop_table('doctor_breaks')
    with op.batch_alter_table('receptionist_shift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receptionist_shift_receptionist_id'))
        batch_op.drop_index(batch_op.f('ix_receptionist_shift_hospital_id'))

    op.drop_table('receptionist_shift')
    op.drop_table('doctor_status')
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_schedule_doctor_id'))

    op.drop_table('doctor_schedule')
    with op.batch_alter_table('doctor_leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_leave_requests_status'))
        batch_op.drop_index(batch_op.f('ix_doctor_leave_requests_doctor_id'))

    op.drop_table('doctor_leave_requests')
    with op.batch_alter_table('doctor_holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_holidays_doctor_id'))

    op.drop_table('doctor_holidays')
    with op.batch_alter_table('doctor_delay_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_delay_logs_doctor_id'))

    op.drop_table('doctor_delay_logs')
    with op.batch_alter_table('receptionists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receptionists_user_id'))
        batch_op.drop_index(batch_op.f('ix_receptionists_hospital_id'))

    op.drop_table('receptionists')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_department_id'))

    op.drop_table('doctors')
    # ### end Alembic commands ###
