"""phase6 subscription reports audit

Revision ID: 6a578fe5e9f7
Revises: 0faa79e4ebe7
Create Date: 2026-06-11 16:07:49.519617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a578fe5e9f7'
down_revision: Union[str, None] = '0faa79e4ebe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('price_annually', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_doctors', sa.Integer(), nullable=False),
    sa.Column('max_departments', sa.Integer(), nullable=False),
    sa.Column('max_tokens_per_day', sa.Integer(), nullable=False),
    sa.Column('sms_quota_monthly', sa.Integer(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('reports_enabled', sa.Boolean(), nullable=False),
    sa.Column('api_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('monthly_reports',
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('unique_patients', sa.Integer(), nullable=False),
    sa.Column('new_patients', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_daily_tokens', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('no_show_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cancellation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('hospital_id', 'month', 'year', name='uq_monthly_report')
    )
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_reports_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('trial_end_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('department_reports',
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('active_doctors', sa.Integer(), nullable=False),
    sa.Column('avg_wait_mins', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('busiest_day', sa.String(length=10), nullable=True),
    sa.Column('busiest_hour', sa.String(length=10), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('department_id', 'month', 'year', name='uq_department_report')
    )
    with op.batch_alter_table('department_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_reports_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_reports_hospital_id'), ['hospital_id'], unique=False)

    op.create_table('invoices',
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('daily_reports',
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('tokens_completed', sa.Integer(), nullable=False),
    sa.Column('tokens_missed', sa.Integer(), nullable=False),
    sa.Column('tokens_cancelled', sa.Integer(), nullable=False),
    sa.Column('avg_wait_mins', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_consult_mins', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peak_hour', sa.String(length=10), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('hospital_id', 'doctor_id', 'report_date', name='uq_daily_report')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_reports_report_date'), ['report_date'], unique=False)

    op.create_table('doctor_reports',
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('completed_tokens', sa.Integer(), nullable=False),
    sa.Column('missed_tokens', sa.Integer(), nullable=False),
    sa.Column('avg_consult_mins', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_wait_mins', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('patient_satisfaction_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_delays_mins', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('doctor_id', 'month', 'year', name='uq_doctor_report')
    )
    with op.batch_alter_table('doctor_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_reports_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_reports_hospital_id'), ['hospital_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_reports_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_reports_doctor_id'))

    op.drop_table('doctor_reports')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_daily_reports_doctor_id'))

    op.drop_table('daily_reports')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_hospital_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('department_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_reports_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_department_reports_department_id'))

    op.drop_table('department_reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_module'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_hospital_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('monthly_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_reports_hospital_id'))

    op.drop_table('monthly_reports')
    op.drop_table('plans')
    # ### end Alembic commands ###
