"""phase4 token engine

Revision ID: c93b2b96f21e
Revises: a75ac41cf226
Create Date: 2026-06-11 15:21:20.790513
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93b2b96f21e'
down_revision: Union[str, None] = 'a75ac41cf226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('patient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=False),
    sa.Column('display_code', sa.String(length=20), nullable=False),
    sa.Column('token_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('estimated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wait_duration_mins', sa.Integer(), nullable=True),
    sa.Column('consult_duration_mins', sa.Integer(), nullable=True),
    sa.Column('is_walkin', sa.Boolean(), nullable=False),
    sa.Column('notified_leave', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_token_date'), ['token_date'], unique=False)

    op.create_table('emergency_queue',
    sa.Column('emergency_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('doctor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('patient_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_phone', sa.String(length=15), nullable=True),
    sa.Column('condition_description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logged_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ),
    sa.PrimaryKeyConstraint('emergency_id')
    )
    with op.batch_alter_table('emergency_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_queue_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_queue_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_queue_status'), ['status'], unique=False)

    op.create_table('token_movement_logs',
    sa.Column('log_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('from_position', sa.Integer(), nullable=True),
    sa.Column('to_position', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('token_movement_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_movement_logs_token_id'), ['token_id'], unique=False)

    op.create_table('token_recall_history',
    sa.Column('recall_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('last_recalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recall_method', sa.String(length=20), nullable=False),
    sa.Column('recalled_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['recalled_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ),
    sa.PrimaryKeyConstraint('recall_id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_table('token_status_history',
    sa.Column('history_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('old_status', sa.String(length=12), nullable=True),
    sa.Column('new_status', sa.String(length=12), nullable=False),
    sa.Column('changed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.token_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('token_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_status_history_token_id'), ['token_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_status_history_token_id'))

    op.drop_table('token_status_history')
    op.drop_table('token_recall_history')
    with op.batch_alter_table('token_movement_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_movement_logs_token_id'))

    op.drop_table('token_movement_logs')
    with op.batch_alter_table('emergency_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_queue_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_queue_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_queue_doctor_id'))

    op.drop_table('emergency_queue')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_token_date'))
        batch_op.drop_index(batch_op.f('ix_tokens_status'))
        batch_op.drop_index(batch_op.f('ix_tokens_patient_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_appointment_id'))

    op.drop_table('tokens')
    # ### end Alembic commands ###
