"""clinic onboarding: hospital status + doctor name

Revision ID: f976596dca29
Revises: 6a578fe5e9f7
Create Date: 2026-06-11 18:33:10.922574
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f976596dca29'
down_revision: Union[str, None] = '6a578fe5e9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=12), nullable=False))
        batch_op.create_index(batch_op.f('ix_hospitals_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
